# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 072a83b0f7da66606f0397970aff9c4fc848d48ca5a1d94f4db32c923b6bb64c8902fef3dbb8a4f47a18d4c88b2565a47d0f6beb841ff8bbc3eeeb3f4daee4ff

test:
  secret_key_base: 265d7d56a6e9e323c926be55d924f5fa93f9d35f3b77ece45cef17283e531030d7b76eb28c8c3a2616736679ea66f68b52970774ab9c8c84966150e4d3ab67b0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
